main:
  banner-mode: "off"
  allow-bean-definition-overriding: true
beaninfo:
  ignore: true
server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
  error:
    whitelabel:
      enabled: false
  datasource:
    url: jdbc:h2:mem:ms-spring?useSSL=false&serverTimezone=UTC
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: true
        format-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus, mappings
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui