main:
  banner-mode: "off"
  allow-bean-definition-overriding: true
beaninfo:
  ignore: true
server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
  error:
    whitelabel:
      enabled: false
  datasource:
    jdbcUrl: jdbc:h2:mem:ms-spring?useSSL=false&serverTimezone=UTC
    username: sa
    password: 12345
management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus, mappings
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui