spring:
  config:
    activate:
      on-profile: local
  application: gateway
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  beaninfo:
    ignore: true
  cloud:
    gateway:
      routes:
        - id: teste
          uri: http://httpbin.org
          predicates:
            - Path=/get
          filters:
            - TokenRelay=
        - id: users
          uri: http://localhost:3000
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay=
        - id: pets
          uri: http://localhost:3005
          predicates:
            - Path=/pets/**
          filters:
            - TokenRelay=
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway-auth-des
            client-secret: EHaorlxJsnsfI4fvwoJDJART5pvOectD
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm
          jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs

server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus, mappings

gateway:
  resourceClient:
      jwtUrl: http://localhost:8080/realms/myrealm/protocol/openid-connect/token
      client-id: gateway-auth-des
      client-secret: EHaorlxJsnsfI4fvwoJDJART5pvOectD
      grantType: password
      scope: "profile email"
  noCsrfEndpoints:
    - "/login"
    - "/users/**"
    - "/pets/**"
  publicEndpoints:
    - "/login"
    - "/users"
    - "/actuator/health"

