version: "3.9"

services:
  db_pet:
    image: mysql:8-debian
    container_name: mysql_db_pet
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pets_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PORT: 3306
    volumes:
      - ./data:/var/lib/db_pet
