version: '3.9'

services:
  db_user:
    image: mysql:8-debian
    container_name: mysql_db_user
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_user
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PORT: 3306
    volumes:
      - ./data:/var/lib/db_user

  db_pet:
    image: mysql:8-debian
    container_name: mysql_db_pet
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db_pet
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PORT: 3306
    volumes:
      - ./data:/var/lib/db_pet

  db_notification:
    image: mysql:8-debian
    container_name: mysql_db_pet
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: db_notification
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PORT: 3306
    volumes:
      - ./data:/var/lib/db_notification

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8080:8080"
    restart: unless-stopped
    command:
      - start-dev
    networks:
      - local-keycloak
