spring:
  config:
    activate:
      on-profile: des
  application: user-api
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  beaninfo:
    ignore: true
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI}
          jwk-set-uri: ${KEYCLOAK_URI}/protocol/openid-connect/certs
  
server:
  port: 3000
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus, mappings

security:
  auth:
    disable: false
  public-endpoints:
    - '/public'
    - "/swagger-ui.html"
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    - "/v2/api-docs/**"
    - "/swagger-resources/**"
  roles:
    ADMIN: [ "ADMIN_PETS" ]
  jwtUrl: ${KEYCLOAK_URI}/protocol/openid-connect/token
  clientId: gateway-auth-des
  clientSecret: 716LgIBZeNVR5WJ3vx5Sg4pcLbxI1tKl