spring:
  config:
    activate:
      on-profile: des
  application: user-api
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  beaninfo:
    ignore: true
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus, mappings