name: Monorepo Java Workflow
run-name: Build ${{ github.run_number }}

on:
  push:
    branches: [ "master", "main", "feature/*", "f/*", "hotfix/*" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "master", "main" ]

env:
  WORKFLOW_PATH: 'murilohenzo/github-actions-deploys/.github/workflows/java_ci.yml@main'

concurrency: pipeline
jobs:
  gateway:
    uses: ${{ env.WORKFLOW_PATH }}
    with:
      project: gateway

  ms-notification:
    uses: ${{ env.WORKFLOW_PATH }}
    with:
      project: ms-notification

  ms-pet-api:
    uses: ${{ env.WORKFLOW_PATH }}
    with:
      project: ms-pet-api

  ms-user:
    uses: ${{ env.WORKFLOW_PATH }}
    with:
      project: ms-user
