name: Monorepo Java Workflow
run-name: Build ${{ github.run_number }}

on:
  push:
    branches: [ "master", "main", "feature/*", "f/*", "hotfix/*" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "master", "main" ]

concurrency: pipeline
jobs:
  gateway:
    uses: murilohenzo/github-actions-deploys/.github/workflows/java_ci.yml@main
    with:
      project: gateway
      run_code_analysis: false
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_TOKEN }}

  ms-notification:
    uses: murilohenzo/github-actions-deploys/.github/workflows/java_ci.yml@main
    with:
      project: ms-notification
      run_code_analysis: false
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_TOKEN }}

  ms-pet-api:
    uses: murilohenzo/github-actions-deploys/.github/workflows/java_ci.yml@main
    with:
      project: ms-pet-api
      run_code_analysis: false
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_TOKEN }}

  ms-user:
    uses: murilohenzo/github-actions-deploys/.github/workflows/java_ci.yml@main
    with:
      project: ms-user
      run_code_analysis: false
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_TOKEN }}

