name: ci-java-workflow

on:
  push:
    branches: [ "master", "main", "feature/*", "f/*", "hotfix/*" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "master", "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Build
      run: mvn clean install -DskipTests
    - name: Unit test
      run: mvn -B org.jacoco:jacoco-maven-plugin:0.8.11:prepare-agent test org.apache.maven.plugins:maven-surefire-report-plugin:3.2.5:report org.jacoco:jacoco-maven-plugin:0.8.11:report
    - name: Exists folder jacoco
      run: ls -la ${{ github.workspace }}/target/site/jacoco
    - name: Get current branch
      run: echo "Current branch is ${{ github.ref }}"
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}