name: ci-java-workflow

on:
  push:
    branches: [ "master", "main", "feature/*", "f/*", "hotfix/*" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "master", "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ci
      url: https://github.com
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Validate branch
      run: |
        current_branch=$(echo "${GITHUB_REF#refs/heads/}")
        echo $current_branch
        if [[ "$current_branch" != "master" && "$current_branch" != "main" && ! "$current_branch" =~ ^(f/|feature/|hotfix/) ]]; then
          echo "Error: Invalid branch name. Branch names must start with 'f/', 'feature/', or 'hotfix/'."
          exit 1
        fi
    - name: Build
      run: mvn clean install -DskipTests
    - name: Unit test
      run: mvn -B org.jacoco:jacoco-maven-plugin:0.8.11:prepare-agent test org.apache.maven.plugins:maven-surefire-report-plugin:3.2.5:report org.jacoco:jacoco-maven-plugin:0.8.11:report
    - name: Report tests
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: ${{ github.workspace }}/target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
    - name: Sonar Cloud
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_PROJECT_KEY }}
        SONAR_PROJECT_KEY: ${{ env.SONAR_PROJECT_KEY }}
        SONAR_ORG: ${{ env.SONAR_ORG_KEY }}
      run: |
        mvn verify sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=$SONAR_ORG \
          -Dsonar.projectKey=$SONAR_PROJECT_KEY